// my-react-app/src/Components/SetHeaders.js
import "./SetHeaders.scss"

export default function SetHeaders() {
  return (
    <div className="header-options">
      <div className="checkbox-option">
        <input type="checkbox" id="row-header" />
        <label htmlFor="row-header">Set 1st row as header</label>
      </div>

      <div className="checkbox-option">
        <input type="checkbox" id="column-header" defaultChecked />
        <label htmlFor="column-header">Set 1st column as header</label>
      </div>

      <div className="checkbox-option">
        <input type="checkbox" id="column-divider" />
        <label htmlFor="column-divider">Show column divider</label>
      </div>

      <div className="header-options2">
        <div className="checkbox-option">
          <input type="checkbox" id="row-divider" />
          <label htmlFor="row-divider">Show row divider</label>
        </div>

        <div className="checkbox-option">
          <input type="checkbox" id="column-title" defaultChecked />
          <label htmlFor="column-title">Show column title</label>
        </div>
      </div>
    </div>
  );
}

// Response Matrix - Angular/Angular11App/src/app/Components/set-headers/set-headers.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-set-headers',
  templateUrl: './set-headers.component.html',
  styleUrls: ['./set-headers.component.scss']
})
export class SetHeadersComponent {

}

<div class="header-options">
  <div class="checkbox-option">
    <input type="checkbox" id="row-header" />
    <label for="row-header">Set 1st row as header</label>
  </div>

  <div class="checkbox-option">
    <input type="checkbox" id="column-header" checked/>
    <label for="column-header">Set 1st column as header</label>
  </div>

  <div class="checkbox-option">
    <input type="checkbox" id="column-divider" />
    <label for="column-divider">Show column divider</label>
  </div>


  <div class="header-options2">
    <div class="checkbox-option">
      <input type="checkbox" id="row-divider" />
      <label for="row-divider">Show row divider</label>
    </div>
  
    <div class="checkbox-option">
      <input type="checkbox" id="column-title" checked/>
      <label for="column-title">Show column title</label>
    </div>
  </div>
</div>
