// Response Matrix - Angular/Angular11App/src/app/Components/matrix-controls/matrix-controls.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-matrix-controls',
  templateUrl: './matrix-controls.component.html',
  styleUrls: ['./matrix-controls.component.scss']
})
export class MatrixControlsComponent {
  isLocked: boolean = true;

  toggleLock() {
    this.isLocked = !this.isLocked; 
  }

  handleSaveClk(){
    alert("Document saved!")
  }
}

<div class="matrix-controls">
    <div class="matrix-info">
      <p>Response Matrix <span>{{ isLocked ? '(Locked)' : '(Unlocked)' }}</span></p>
    </div>
    <div class="control-buttons">
      <button class="unlock-btn" (click)="toggleLock()">
          <img [src]="isLocked ? 'assets/locked-img.png' : 'assets/unlocked-img.PNG'">
          <span>{{ isLocked ? 'UNLOCK' : 'LOCK' }}</span>
      </button>
      <button class="preview-btn" (click) = "handleSaveClk()">
          <img src="assets/preview-img.PNG">
          <span>SAVE AND PREVIEW</span>
      </button>
    </div>
  </div>

// my-react-app/src/Components/MatrixControls.js
import { useState } from "react";
import './MatrixControls.scss';
import lockedImg from "../assets/locked-img.png";
import unlockedImg from "../assets/unlocked-img.PNG";
import previewImg from "../assets/preview-img.PNG"

export default function MatrixControls() {

    const [isLocked, toggleLock] = useState(true);

    return (
        <div className="matrix-controls">
            <div className="matrix-info">
                <p>Response Matrix <span>{isLocked ? '(Locked)' : '(Unlocked)'}</span></p>
            </div>
            <div className="control-buttons">
                <button className="unlock-btn" onClick={() => toggleLock(isLocked? false : true)}>
                    <img src={isLocked ? lockedImg : unlockedImg} />
                    <span>{isLocked ? 'UNLOCK' : 'LOCK'}</span>
                </button>

                <button className="preview-btn" onClick={() => alert("Saved!")}>
                    <img src={previewImg}/>
                    <span>SAVE AND PREVIEW</span>
                </button>
            </div>
        </div>

    )
}
