// Response Matrix - Angular/Angular11App/src/app/Components/question-name/question-name.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-question-name',
  templateUrl: './question-name.component.html',
  styleUrls: ['./question-name.component.scss']
})
export class QuestionNameComponent {
  question: string = '';  
}

<div class="question-name">
  <label for="questionInput">Question (Stem)*</label>
  <input
    id="questionInput"
    type="text"
    placeholder="Enter Question (Stem)"
    [(ngModel)]="question"
  />
</div>

// my-react-app/src/Components/QuestionName.js
import "./QuestionName.scss"

export default function () {
    return (
        <div className="question-name">
            <label htmlFor="questionInput">Question (Stem)*</label>
            <input
                id="questionInput"
                type="text"
                placeholder="Enter Question (Stem)"
            />
        </div>

    )
}
